// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolarisPlatform.Infrastructure.Persistence.Context;

#nullable disable

namespace SolarisPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(SolarisDbContext))]
    [Migration("20260210041843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.Banco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreCorto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_corto");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<long?>("PaisId")
                        .HasColumnType("bigint")
                        .HasColumnName("pais_id");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PaisId");

                    b.ToTable("banco", "cat");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.Ciudad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<long>("EstadoProvinciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("estado_provincia_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("EstadoProvinciaId");

                    b.ToTable("ciudad", "cat");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.EstadoProvincia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<long>("PaisId")
                        .HasColumnType("bigint")
                        .HasColumnName("pais_id");

                    b.HasKey("Id");

                    b.HasIndex("PaisId", "Codigo")
                        .IsUnique();

                    b.ToTable("estado_provincia", "cat");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.FormaPago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<int>("DiasCredito")
                        .HasColumnType("integer")
                        .HasColumnName("dias_credito");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<bool>("RequiereBanco")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_banco");

                    b.Property<bool>("RequiereReferencia")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_referencia");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("forma_pago", "cat");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.Impuesto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("EsRetencion")
                        .HasColumnType("boolean")
                        .HasColumnName("es_retencion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje");

                    b.Property<string>("TipoImpuesto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_impuesto");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("impuesto", "cat");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.Moneda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<short>("DecimalesPermitidos")
                        .HasColumnType("smallint")
                        .HasColumnName("decimales_permitidos");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("simbolo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("moneda", "cat");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.Pais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Bandera")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bandera");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoIso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("codigo_iso2");

                    b.Property<string>("CodigoTelefonico")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_telefonico");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreIngles")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_ingles");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CodigoIso2")
                        .IsUnique();

                    b.ToTable("pais", "cat");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.TipoIdentificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("AplicaEmpresa")
                        .HasColumnType("boolean")
                        .HasColumnName("aplica_empresa");

                    b.Property<bool>("AplicaPersona")
                        .HasColumnType("boolean")
                        .HasColumnName("aplica_persona");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("Longitud")
                        .HasColumnType("integer")
                        .HasColumnName("longitud");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<long?>("PaisId")
                        .HasColumnType("bigint")
                        .HasColumnName("pais_id");

                    b.Property<string>("Patron")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patron");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PaisId");

                    b.ToTable("tipo_identificacion", "cat");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Empresas.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("DireccionFiscal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("direccion_fiscal");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<DateTime?>("FechaFinContrato")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_contrato");

                    b.Property<DateTime>("FechaInicioContrato")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_contrato");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo");

                    b.Property<int>("MaxUsuarios")
                        .HasColumnType("integer")
                        .HasColumnName("max_usuarios");

                    b.Property<long?>("MonedaPrincipalId")
                        .HasColumnType("bigint")
                        .HasColumnName("moneda_principal_id");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_identificacion");

                    b.Property<string>("PaginaWeb")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("pagina_web");

                    b.Property<long?>("PaisId")
                        .HasColumnType("bigint")
                        .HasColumnName("pais_id");

                    b.Property<string>("PlanContratado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_contratado");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_identificacion");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_eliminacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zona_horaria");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("MonedaPrincipalId");

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.HasIndex("PaisId");

                    b.ToTable("empresa", "emp");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Empresas.Sucursal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<long?>("CiudadId")
                        .HasColumnType("bigint")
                        .HasColumnName("ciudad_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("direccion");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<long?>("EstadoProvinciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("estado_provincia_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitud");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<long?>("PaisId")
                        .HasColumnType("bigint")
                        .HasColumnName("pais_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_eliminacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EstadoProvinciaId");

                    b.HasIndex("PaisId");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique();

                    b.ToTable("sucursal", "emp");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Modulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsMenu")
                        .HasColumnType("boolean")
                        .HasColumnName("es_menu");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icono");

                    b.Property<long?>("ModuloPadreId")
                        .HasColumnType("bigint")
                        .HasColumnName("modulo_padre_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Ruta")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ruta");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ModuloPadreId");

                    b.ToTable("modulo", "seg");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Permiso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<long>("ModuloId")
                        .HasColumnType("bigint")
                        .HasColumnName("modulo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoPermiso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_permiso");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ModuloId");

                    b.ToTable("permiso", "seg");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("es_sistema");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icono");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_eliminacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Codigo", "EmpresaId")
                        .IsUnique();

                    b.ToTable("rol", "seg");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.RolPermiso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<long>("PermisoId")
                        .HasColumnType("bigint")
                        .HasColumnName("permiso_id");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId", "PermisoId")
                        .IsUnique();

                    b.ToTable("rol_permiso", "seg");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.SesionUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("CerradaPorUsuario")
                        .HasColumnType("boolean")
                        .HasColumnName("cerrada_por_usuario");

                    b.Property<string>("CiudadAcceso")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad_acceso");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direccion_ip");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dispositivo");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime>("FechaUltimaActividad")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_actividad");

                    b.Property<string>("Navegador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("navegador");

                    b.Property<string>("PaisAcceso")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais_acceso");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("SistemaOperativo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sistema_operativo");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken");

                    b.HasIndex("Token");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sesion_usuario", "seg");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verificado");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaBloqueo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_bloqueo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<DateTime?>("FechaExpiracionRecuperacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion_recuperacion");

                    b.Property<DateTime?>("FechaExpiracionToken")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion_token");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime?>("FechaUltimoCambioPassword")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultimo_cambio_password");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<char?>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("genero");

                    b.Property<string>("IdiomaPreferido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("idioma_preferido");

                    b.Property<int>("IntentosLoginFallidos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos_login_fallidos");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroIdentificacion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_identificacion");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_salt");

                    b.Property<bool>("RequiereCambioPassword")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_cambio_password");

                    b.Property<long?>("SucursalId")
                        .HasColumnType("bigint")
                        .HasColumnName("sucursal_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TemaPreferido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tema_preferido");

                    b.Property<long?>("TipoIdentificacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_identificacion_id");

                    b.Property<string>("TokenRecuperacion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_recuperacion");

                    b.Property<string>("TokenVerificacionEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_verificacion_email");

                    b.Property<bool>("TwoFactorHabilitado")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_habilitado");

                    b.Property<string>("TwoFactorSecretKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("two_factor_secret_key");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_eliminacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("ZonaHoraria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zona_horaria");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Estado");

                    b.HasIndex("SucursalId");

                    b.ToTable("usuario", "seg");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.UsuarioRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("usuario_rol", "seg");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.UsuarioSucursal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<long>("SucursalId")
                        .HasColumnType("bigint")
                        .HasColumnName("sucursal_id");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId", "SucursalId")
                        .IsUnique();

                    b.ToTable("usuario_sucursal", "seg");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.Banco", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Catalogos.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.Ciudad", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Catalogos.EstadoProvincia", "EstadoProvincia")
                        .WithMany("Ciudades")
                        .HasForeignKey("EstadoProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoProvincia");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.EstadoProvincia", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Catalogos.Pais", "Pais")
                        .WithMany("EstadosProvincias")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.FormaPago", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.Impuesto", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.TipoIdentificacion", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Catalogos.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Empresas.Empresa", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Catalogos.Moneda", "MonedaPrincipal")
                        .WithMany()
                        .HasForeignKey("MonedaPrincipalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolarisPlatform.Domain.Entities.Catalogos.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MonedaPrincipal");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Empresas.Sucursal", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Catalogos.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolarisPlatform.Domain.Entities.Empresas.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolarisPlatform.Domain.Entities.Catalogos.EstadoProvincia", "EstadoProvincia")
                        .WithMany()
                        .HasForeignKey("EstadoProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolarisPlatform.Domain.Entities.Catalogos.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ciudad");

                    b.Navigation("Empresa");

                    b.Navigation("EstadoProvincia");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Modulo", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Seguridad.Modulo", "ModuloPadre")
                        .WithMany("SubModulos")
                        .HasForeignKey("ModuloPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModuloPadre");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Permiso", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Seguridad.Modulo", "Modulo")
                        .WithMany("Permisos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Rol", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.RolPermiso", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Seguridad.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolarisPlatform.Domain.Entities.Seguridad.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.SesionUsuario", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolarisPlatform.Domain.Entities.Empresas.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.UsuarioRol", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Seguridad.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolarisPlatform.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.UsuarioSucursal", b =>
                {
                    b.HasOne("SolarisPlatform.Domain.Entities.Empresas.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolarisPlatform.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany("UsuarioSucursales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.EstadoProvincia", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Catalogos.Pais", b =>
                {
                    b.Navigation("EstadosProvincias");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Empresas.Empresa", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Modulo", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("SubModulos");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("SolarisPlatform.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.Navigation("Sesiones");

                    b.Navigation("UsuarioRoles");

                    b.Navigation("UsuarioSucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
